spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sping5?serverTimezone=UTC
    username: root
    password: 522307026
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:com/thyo/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true



